"""add_foto_perfil_url_to_musicos_table

Revision ID: 442b9e7f242c
Revises: 
Create Date: 2025-06-05 17:09:29.737948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '442b9e7f242c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musicos', sa.Column('foto_perfil_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('musicos', 'foto_perfil_url')
    # ### end Alembic commands ###
